name: 'My Custom Action'
description: 'Intalling and Caching NPM packages'
inputs:
  path-of-folder: #id of input
    descripton: path of folder
    required: true
runs:
  using: "composite"
  steps:
    - name: cache npm dependencies
      uses: actions/cache@v3
      with:
        path: ${{inputs.path-of-folder}}
        key: ${{runner.os}}-node-modules-${{hashFiles('package-lock.json')}}

    - name: Install Dependencies
      run: npm install
      shell: bash